"""Package for pipeline execution framework"""

from __future__ import absolute_import

try:
    # version.py is auto-generated by sconsUtils
    from .version import *  # noqa: F403
except:
    __version__ = "unknown"

from .graphBuilder import *
from .pipeline import *
from .pipelineBuilder import *
from .graph import *
from .taskLoader import *
